/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgot-password/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/_dashboard/index'
import { Route as AppDashboardStaffIndexRouteImport } from './routes/_app/_dashboard/staff/index'
import { Route as AppDashboardSoundEffectsIndexRouteImport } from './routes/_app/_dashboard/sound-effects/index'
import { Route as AppDashboardSettingsIndexRouteImport } from './routes/_app/_dashboard/settings/index'
import { Route as AppDashboardHomeSlidesIndexRouteImport } from './routes/_app/_dashboard/home-slides/index'
import { Route as AppDashboardCategoriesIndexRouteImport } from './routes/_app/_dashboard/categories/index'
import { Route as AppDashboardBooksIndexRouteImport } from './routes/_app/_dashboard/books/index'
import { Route as AppDashboardBackgroundMusicIndexRouteImport } from './routes/_app/_dashboard/background-music/index'
import { Route as AppDashboardAppUsersIndexRouteImport } from './routes/_app/_dashboard/app-users/index'
import { Route as AppDashboardBooksBookIdIndexRouteImport } from './routes/_app/_dashboard/books/$bookId/index'

const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/_dashboard/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardStaffIndexRoute = AppDashboardStaffIndexRouteImport.update({
  id: '/_dashboard/staff/',
  path: '/staff/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardSoundEffectsIndexRoute =
  AppDashboardSoundEffectsIndexRouteImport.update({
    id: '/_dashboard/sound-effects/',
    path: '/sound-effects/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardSettingsIndexRoute =
  AppDashboardSettingsIndexRouteImport.update({
    id: '/_dashboard/settings/',
    path: '/settings/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardHomeSlidesIndexRoute =
  AppDashboardHomeSlidesIndexRouteImport.update({
    id: '/_dashboard/home-slides/',
    path: '/home-slides/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardCategoriesIndexRoute =
  AppDashboardCategoriesIndexRouteImport.update({
    id: '/_dashboard/categories/',
    path: '/categories/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardBooksIndexRoute = AppDashboardBooksIndexRouteImport.update({
  id: '/_dashboard/books/',
  path: '/books/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardBackgroundMusicIndexRoute =
  AppDashboardBackgroundMusicIndexRouteImport.update({
    id: '/_dashboard/background-music/',
    path: '/background-music/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardAppUsersIndexRoute =
  AppDashboardAppUsersIndexRouteImport.update({
    id: '/_dashboard/app-users/',
    path: '/app-users/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardBooksBookIdIndexRoute =
  AppDashboardBooksBookIdIndexRouteImport.update({
    id: '/_dashboard/books/$bookId/',
    path: '/books/$bookId/',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forbidden': typeof ForbiddenRoute
  '/': typeof AppDashboardIndexRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/app-users': typeof AppDashboardAppUsersIndexRoute
  '/background-music': typeof AppDashboardBackgroundMusicIndexRoute
  '/books': typeof AppDashboardBooksIndexRoute
  '/categories': typeof AppDashboardCategoriesIndexRoute
  '/home-slides': typeof AppDashboardHomeSlidesIndexRoute
  '/settings': typeof AppDashboardSettingsIndexRoute
  '/sound-effects': typeof AppDashboardSoundEffectsIndexRoute
  '/staff': typeof AppDashboardStaffIndexRoute
  '/books/$bookId': typeof AppDashboardBooksBookIdIndexRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof ForbiddenRoute
  '/': typeof AppDashboardIndexRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/app-users': typeof AppDashboardAppUsersIndexRoute
  '/background-music': typeof AppDashboardBackgroundMusicIndexRoute
  '/books': typeof AppDashboardBooksIndexRoute
  '/categories': typeof AppDashboardCategoriesIndexRoute
  '/home-slides': typeof AppDashboardHomeSlidesIndexRoute
  '/settings': typeof AppDashboardSettingsIndexRoute
  '/sound-effects': typeof AppDashboardSoundEffectsIndexRoute
  '/staff': typeof AppDashboardStaffIndexRoute
  '/books/$bookId': typeof AppDashboardBooksBookIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/_app/_dashboard/': typeof AppDashboardIndexRoute
  '/_auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/_app/_dashboard/app-users/': typeof AppDashboardAppUsersIndexRoute
  '/_app/_dashboard/background-music/': typeof AppDashboardBackgroundMusicIndexRoute
  '/_app/_dashboard/books/': typeof AppDashboardBooksIndexRoute
  '/_app/_dashboard/categories/': typeof AppDashboardCategoriesIndexRoute
  '/_app/_dashboard/home-slides/': typeof AppDashboardHomeSlidesIndexRoute
  '/_app/_dashboard/settings/': typeof AppDashboardSettingsIndexRoute
  '/_app/_dashboard/sound-effects/': typeof AppDashboardSoundEffectsIndexRoute
  '/_app/_dashboard/staff/': typeof AppDashboardStaffIndexRoute
  '/_app/_dashboard/books/$bookId/': typeof AppDashboardBooksBookIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forbidden'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/app-users'
    | '/background-music'
    | '/books'
    | '/categories'
    | '/home-slides'
    | '/settings'
    | '/sound-effects'
    | '/staff'
    | '/books/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/app-users'
    | '/background-music'
    | '/books'
    | '/categories'
    | '/home-slides'
    | '/settings'
    | '/sound-effects'
    | '/staff'
    | '/books/$bookId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/forbidden'
    | '/_app/_dashboard/'
    | '/_auth/forgot-password/'
    | '/_auth/login/'
    | '/_auth/reset-password/'
    | '/_app/_dashboard/app-users/'
    | '/_app/_dashboard/background-music/'
    | '/_app/_dashboard/books/'
    | '/_app/_dashboard/categories/'
    | '/_app/_dashboard/home-slides/'
    | '/_app/_dashboard/settings/'
    | '/_app/_dashboard/sound-effects/'
    | '/_app/_dashboard/staff/'
    | '/_app/_dashboard/books/$bookId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password/': {
      id: '/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/_dashboard/': {
      id: '/_app/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_dashboard/staff/': {
      id: '/_app/_dashboard/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppDashboardStaffIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_dashboard/sound-effects/': {
      id: '/_app/_dashboard/sound-effects/'
      path: '/sound-effects'
      fullPath: '/sound-effects'
      preLoaderRoute: typeof AppDashboardSoundEffectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_dashboard/settings/': {
      id: '/_app/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppDashboardSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_dashboard/home-slides/': {
      id: '/_app/_dashboard/home-slides/'
      path: '/home-slides'
      fullPath: '/home-slides'
      preLoaderRoute: typeof AppDashboardHomeSlidesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_dashboard/categories/': {
      id: '/_app/_dashboard/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppDashboardCategoriesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_dashboard/books/': {
      id: '/_app/_dashboard/books/'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof AppDashboardBooksIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_dashboard/background-music/': {
      id: '/_app/_dashboard/background-music/'
      path: '/background-music'
      fullPath: '/background-music'
      preLoaderRoute: typeof AppDashboardBackgroundMusicIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_dashboard/app-users/': {
      id: '/_app/_dashboard/app-users/'
      path: '/app-users'
      fullPath: '/app-users'
      preLoaderRoute: typeof AppDashboardAppUsersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_dashboard/books/$bookId/': {
      id: '/_app/_dashboard/books/$bookId/'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof AppDashboardBooksBookIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDashboardAppUsersIndexRoute: typeof AppDashboardAppUsersIndexRoute
  AppDashboardBackgroundMusicIndexRoute: typeof AppDashboardBackgroundMusicIndexRoute
  AppDashboardBooksIndexRoute: typeof AppDashboardBooksIndexRoute
  AppDashboardCategoriesIndexRoute: typeof AppDashboardCategoriesIndexRoute
  AppDashboardHomeSlidesIndexRoute: typeof AppDashboardHomeSlidesIndexRoute
  AppDashboardSettingsIndexRoute: typeof AppDashboardSettingsIndexRoute
  AppDashboardSoundEffectsIndexRoute: typeof AppDashboardSoundEffectsIndexRoute
  AppDashboardStaffIndexRoute: typeof AppDashboardStaffIndexRoute
  AppDashboardBooksBookIdIndexRoute: typeof AppDashboardBooksBookIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDashboardAppUsersIndexRoute: AppDashboardAppUsersIndexRoute,
  AppDashboardBackgroundMusicIndexRoute: AppDashboardBackgroundMusicIndexRoute,
  AppDashboardBooksIndexRoute: AppDashboardBooksIndexRoute,
  AppDashboardCategoriesIndexRoute: AppDashboardCategoriesIndexRoute,
  AppDashboardHomeSlidesIndexRoute: AppDashboardHomeSlidesIndexRoute,
  AppDashboardSettingsIndexRoute: AppDashboardSettingsIndexRoute,
  AppDashboardSoundEffectsIndexRoute: AppDashboardSoundEffectsIndexRoute,
  AppDashboardStaffIndexRoute: AppDashboardStaffIndexRoute,
  AppDashboardBooksBookIdIndexRoute: AppDashboardBooksBookIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
